version: "3.9"

services:
  app:
    container_name: pong-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ponghospital-app:latest
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5000:5000"   # HTTP ของ app บน host
    volumes:
      - ./ssl:/app/ssl:ro
    networks:
      - pong-net

  nginx:
    image: nginx:1.25-alpine
    container_name: pong-nginx
    restart: unless-stopped
    ports:
      - "8081:80"     # HTTP ของ nginx
      - "8444:443"    # HTTPS ของ nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pong-net

networks:
  pong-net:
    external: true
